client localhost{
 ipaddr = 127.0.0.1
 secret = testing123
 require_message_authenticator = no
 nastype = other
}
client 192.168.33.48 {
 secret = Pilakaknada123
 shortname = K12_user-sw-1
}
client 192.168.33.49 {
 secret = Pilakaknada123
 shortname = K12_user-sw-2
}
client 192.168.33.50 {
 secret = Pilakaknada123
 shortname = K12_user-sw-3
}
client 192.168.33.60 {
 secret = Pilakaknada123
 shortname = K12_user-sw-4
}
client 192.168.133.46 {
 secret = Pilakaknada123
 shortname = M3_user-sw-1
}
client 192.168.133.47 {
 secret = Pilakaknada123
 shortname = M3_user-sw-2
}
client 192.168.133.48 {
 secret = Pilakaknada123
 shortname = M3_user-sw-3
}
client 192.168.133.49 {
 secret = Pilakaknada123
 shortname = M3_user-sw-4
}
client 192.168.133.50 {
 secret = Pilakaknada123
 shortname = M5_user-sw-5
}
client 192.168.33.51 {
 secret = Pilakaknada123
 shortname = K12_user-sw-5
}
client 192.168.33.55 {
 secret = Pilakaknada123
 shortname = K12_user-sw-n
}
client 192.168.33.56 {
 secret = Pilakaknada123
 shortname = K12_user-sw-3800
}
client 192.168.33.150 {
 secret = RBP@FreeRD!2
 shortname = Fortiswitch 448E
}
client 192.168.133.56 {
 secret = Pilakaknada123
 shortname = M3-USw7-216kab
}
client 192.168.133.57 {
 secret = Pilakaknada123
 shortname = M5_Usw7_Peteris
}
client 192.168.133.58 {
 secret = Pilakaknada123
 shortname = M3-Usw-Edgars
}
